### PR TITLE
More icon changing options

### PR DESCRIPTION
**Pull request by jeep70**
Adds four options for the icon: default (as it is now), light (matches with breeze dark), dark (matches with breeze light), and the custom option as it is now. The configuration dialog is also rearranged a bit to make it fit in better. It might be good in the future to make the older options fit more with the newer ones, such as making the konsole and yakuake options radio buttons instead of individually labeled checkboxes

### CODE REVIEW

**Comment by I-Dream-in-Code** [comment]
Konsole and yakuake are check boxes because there is still an option to run pacman -Syu in the background if neither are selected

**Comment by I-Dream-in-Code** [comment]
That's exactly why i have it as checkboxes

It's too cluttered plus background only works if aur support is disabled

Background won't work for aur

**Comment by jeep70** [comment]
Well, suit yourself. Is there anything you want me to change in this pull request?

**Comment by I-Dream-in-Code** [comment]
Checked it out

Switching to light or dark doesn't change anything for me.

Also when I restart my plasmashell for light and dark and open settings again it's still on the "default" radio button

Custom ones stays though

**Comment by I-Dream-in-Code** [comment]
Going from custom to default doesn't set it back again either

**Comment by I-Dream-in-Code** [comment]
it appears you never uploaded the new icons to this pull request

**Comment by jeep70** [comment]
Wow, I don't know how that happened. They should be in now

**Comment by jeep70** [comment]
The only thing is if you don't approve the authentication request, the radio button will stay without the state changing

**Comment by I-Dream-in-Code** [comment]
I did approve it
Restarted plasma shell
Opened settings
Was still selected as default

**Comment by jeep70** [comment]
https://streamable.com/rx6mp working here (assuming you updated to the commit i just pushed with the images actually included)

**Comment by I-Dream-in-Code** [comment]
I'll check it again tomorrow

Need to pull an early shift at work

**Comment by I-Dream-in-Code** [comment]
Hey just wanted to say thanks for cleaning up the mess of the config qml file.  been meaning to get around to it

**Comment by jeep70** [comment]
No problem, glad I helped

**Pull request merged**
