### PR TITLE
Autohide icon in systemtray

### PR DESCRIPTION
**Pull request by naraesk**
fixes issue #5

### CODE REVIEW

**Comment by I-Dream-in-Code** [comment]
@naraesk it's not autohiding for me unless I have to set something in the panel?

**Comment by naraesk** [comment]
You have to set visibility manually to "Automatic" in the panel settings. Don't know if it's possible to provide this as a default.

**Comment by naraesk** [comment]
did it work?

**Comment by I-Dream-in-Code** [comment]
I'll check it in a bit had to setup new computer

**Pull request merged**
