### PR TITLE
SVG icons and bug fixes

### PR DESCRIPTION
**Pull request by jurplel**
- Icons converted to SVG
- Renamed icons
- Icons are now colored the same as breeze and breeze dark icons
- Fixed radio buttons not synchronizing properly with the icon state

### CODE REVIEW

**Comment by I-Dream-in-Code** [comment]
still broken

won't even show icon now
kde-512

**Comment by I-Dream-in-Code** [comment]
when trying to open chosen.svg from /usr/share/plasma/plasmoids/org.kde.archUpdate/contents/images in inkscape 
image

**Comment by jurplel** [comment]
It's because it's expecting an SVG icon.

**Comment by I-Dream-in-Code** [comment]
yeah pretty sure implicit conversion to svg won't fly.

You can use `convert` maybe?

**Comment by jurplel** [comment]
I don't wanna add any extra dependencies - This should work by making Qt resolve the file extension implicitly

**Comment by I-Dream-in-Code** [comment]
great work thanks for the contribution

**Pull request merged**
